/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JReverseHelperMethods */

#ifndef _Included_JReverseHelperMethods
#define _Included_JReverseHelperMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JReverseHelperMethods
 * Method:    getClassInstacnes
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_JReverseHelperMethods_getClassInstacnes
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
