/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jreverse_jreverse_Core_JReverseScriptingCore */

#ifndef _Included_com_jreverse_jreverse_Core_JReverseScriptingCore
#define _Included_com_jreverse_jreverse_Core_JReverseScriptingCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jreverse_jreverse_Core_JReverseScriptingCore
 * Method:    GetClassInstances
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jreverse_jreverse_Core_JReverseScriptingCore_GetClassInstances
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
