/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jreverse_jreverse_PipeManager_PipeManager */

#ifndef _Included_com_jreverse_jreverse_PipeManager_PipeManager
#define _Included_com_jreverse_jreverse_PipeManager_PipeManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jreverse_jreverse_PipeManager_PipeManager
 * Method:    GetLoadedPipes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jreverse_jreverse_PipeManager_PipeManager_GetLoadedPipes
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
