/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jreverse_jreverse_PipeManager_PipeManager */

#ifndef _Included_com_jreverse_jreverse_PipeManager_PipeManager
#define _Included_com_jreverse_jreverse_PipeManager_PipeManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jreverse_jreverse_PipeManager_PipeManager
 * Method:    InitAPI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jreverse_jreverse_PipeManager_PipeManager_InitAPI
  (JNIEnv *, jclass);

/*
 * Class:     com_jreverse_jreverse_PipeManager_PipeManager
 * Method:    GetLoadedPipes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jreverse_jreverse_PipeManager_PipeManager_GetLoadedPipes
  (JNIEnv *, jclass);

/*
 * Class:     com_jreverse_jreverse_PipeManager_PipeManager
 * Method:    GetPipeInfo
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jreverse_jreverse_PipeManager_PipeManager_GetPipeInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jreverse_jreverse_PipeManager_PipeManager
 * Method:    AddPipe
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jreverse_jreverse_PipeManager_PipeManager_AddPipe
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_jreverse_jreverse_PipeManager_PipeManager
 * Method:    RemovePipe
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jreverse_jreverse_PipeManager_PipeManager_RemovePipe
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
